// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeGoogleDrive(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AuthorizeGoogleDrive'](arg1, arg2, arg3, arg4);
}

export function BrowseForFolder(arg1) {
  return window['go']['main']['App']['BrowseForFolder'](arg1);
}

export function ConfigExists() {
  return window['go']['main']['App']['ConfigExists']();
}

export function DefaultCloudRoot(arg1) {
  return window['go']['main']['App']['DefaultCloudRoot'](arg1);
}

export function DetectSavePath() {
  return window['go']['main']['App']['DetectSavePath']();
}

export function ExpectedSavePath() {
  return window['go']['main']['App']['ExpectedSavePath']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGoogleDriveMirrorStatus() {
  return window['go']['main']['App']['GetGoogleDriveMirrorStatus']();
}

export function GetLogTail() {
  return window['go']['main']['App']['GetLogTail']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PromoteConflict(arg1) {
  return window['go']['main']['App']['PromoteConflict'](arg1);
}

export function ResolveConflict(arg1) {
  return window['go']['main']['App']['ResolveConflict'](arg1);
}

export function RunRecover() {
  return window['go']['main']['App']['RunRecover']();
}

export function RunSetup(arg1, arg2) {
  return window['go']['main']['App']['RunSetup'](arg1, arg2);
}

export function RunUndo() {
  return window['go']['main']['App']['RunUndo']();
}
