// Package bisync sets up a real local mirror directory kept in sync with a
// Google Drive folder via `rclone bisync` on a systemd user timer.
//
// This exists only because Google ships no native Linux sync client
// (unlike Dropbox and OneDrive, which stay out of this package entirely —
// they already maintain a real local folder themselves). A FUSE mount
// would be simpler to wire up, but it streams reads/writes over the
// network live, which is exactly the failure mode that makes Google
// Drive's own Windows "Streaming" mode unsafe for an actively-written
// save file. A real local directory, periodically reconciled, avoids that.
package bisync

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"
)

const (
	ServiceName = "shogun2sync-gdrive-bisync"

	// MinRcloneMajor/Minor is the oldest rclone that understands the flags
	// below. --recover, --max-lock and the --conflict-* family all landed
	// together in rclone 1.66.0 (March 2024). On anything older the timer
	// would fail on every single run with "unknown flag", so this is
	// checked up front where we can still say something useful.
	MinRcloneMajor = 1
	MinRcloneMinor = 66
)

// Available reports whether this mechanism applies on this OS at all.
func Available() bool {
	return runtime.GOOS == "linux"
}

var versionRe = regexp.MustCompile(`v(\d+)\.(\d+)(?:\.(\d+))?`)

// Version returns the installed rclone's major and minor version.
func Version(ctx context.Context) (major, minor int, err error) {
	out, err := exec.CommandContext(ctx, "rclone", "version").Output()
	if err != nil {
		return 0, 0, fmt.Errorf("running rclone version: %w", err)
	}
	m := versionRe.FindStringSubmatch(string(out))
	if m == nil {
		return 0, 0, fmt.Errorf("could not read a version number out of %q", strings.TrimSpace(string(out)))
	}
	major, _ = strconv.Atoi(m[1])
	minor, _ = strconv.Atoi(m[2])
	return major, minor, nil
}

// CheckVersion reports a friendly error if rclone is too old to drive.
func CheckVersion(ctx context.Context) error {
	major, minor, err := Version(ctx)
	if err != nil {
		return err
	}
	if major > MinRcloneMajor || (major == MinRcloneMajor && minor >= MinRcloneMinor) {
		return nil
	}
	return fmt.Errorf(
		"rclone %d.%d is too old for reliable syncing (need %d.%d or newer). "+
			"Update it with your package manager, or install the current version from https://rclone.org/install/",
		major, minor, MinRcloneMajor, MinRcloneMinor)
}

// shellQuote wraps s for safe use inside single quotes in the generated
// script. A path is player-chosen and can contain anything, apostrophes
// included.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// systemdEscape protects a value used in a unit file. systemd expands "%"
// as the start of a specifier, so a literal one has to be doubled or the
// path silently turns into something else.
func systemdEscape(s string) string {
	return strings.ReplaceAll(s, "%", "%%")
}

// syncScript is the body of the script the timer runs.
//
// It's a real file rather than an inline `sh -c '...'` in the unit because
// that inline form has to survive two layers of quoting (systemd's, then
// the shell's), and gets both a percent sign and an apostrophe in a path
// wrong. A file has neither problem and is also something a player can
// read when they want to know what's running on their machine.
func syncScript(rclonePath, localDir, remote, logPath string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by Shogun 2 Save Sync. Edits will be overwritten.
set -u

RCLONE=%s
LOCAL=%s
REMOTE=%s
LOG=%s

"$RCLONE" bisync "$LOCAL" "$REMOTE" \
  --resilient --recover --max-lock 2m \
  --conflict-resolve newer --conflict-loser num --conflict-suffix conflict \
  --create-empty-src-dirs --drive-skip-gdocs \
  --log-file "$LOG" --log-format date,time -v
status=$?

if [ "$status" -eq 0 ]; then
  exit 0
fi

# Exit 7 is a critical abort: rclone will refuse every later run until a
# --resync re-establishes the baseline. Doing that automatically is
# normally dangerous, because --resync picks a winner and can overwrite
# the other player's newer save. The one case where it's safe is a local
# folder with nothing in it -- which is also the case that lands here most
# often, since bisync treats a legitimately empty folder as
# indistinguishable from a mount that dropped out.
if [ "$status" -eq 7 ] && [ -z "$(ls -A "$LOCAL" 2>/dev/null)" ]; then
  exec "$RCLONE" bisync "$LOCAL" "$REMOTE" --resync --create-empty-src-dirs \
    --log-file "$LOG" --log-format date,time -v
fi

exit "$status"
`, shellQuote(rclonePath), shellQuote(localDir), shellQuote(remote), shellQuote(logPath))
}

// Paths returns where the generated script and its log live.
func Paths() (scriptPath, logPath string, err error) {
	base, err := os.UserConfigDir()
	if err != nil {
		return "", "", err
	}
	dir := filepath.Join(base, "shogun2sync")
	return filepath.Join(dir, "gdrive-bisync.sh"), filepath.Join(dir, "gdrive-bisync.log"), nil
}

// EnsureMirror establishes (or re-establishes) a bisync baseline between
// localDir and remoteName:remoteSubfolder, then installs and enables a
// systemd --user timer that keeps them in sync.
func EnsureMirror(ctx context.Context, remoteName, remoteSubfolder, localDir string) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("bisync is only needed on Linux")
	}
	rclonePath, err := exec.LookPath("rclone")
	if err != nil {
		return fmt.Errorf("rclone is not installed")
	}
	if _, err := exec.LookPath("systemctl"); err != nil {
		return fmt.Errorf("systemctl is not available")
	}
	if err := CheckVersion(ctx); err != nil {
		return err
	}
	if remoteSubfolder == "" {
		// Without this an empty subfolder would mirror the player's entire
		// Drive into a game-saves folder.
		return fmt.Errorf("refusing to mirror the whole Drive: no sync folder was given")
	}

	if err := os.MkdirAll(localDir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", localDir, err)
	}

	remote := remoteName + ":" + remoteSubfolder

	baseline := exec.CommandContext(ctx, rclonePath, "bisync", localDir, remote,
		"--resync", "--create-empty-src-dirs")
	if out, err := baseline.CombinedOutput(); err != nil {
		return fmt.Errorf("initial sync failed: %w: %s", err, out)
	}

	scriptPath, logPath, err := Paths()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(scriptPath, []byte(syncScript(rclonePath, localDir, remote, logPath)), 0o755); err != nil {
		return fmt.Errorf("writing %s: %w", scriptPath, err)
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	systemdDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(systemdDir, 0o755); err != nil {
		return err
	}

	shPath, err := exec.LookPath("sh")
	if err != nil {
		return err
	}

	serviceContents := fmt.Sprintf(`[Unit]
Description=Sync the Shogun 2 save folder with Google Drive

[Service]
Type=oneshot
ExecStart=%s %s
`, systemdEscape(shPath), systemdEscape(scriptPath))

	timerContents := `[Unit]
Description=Run the Shogun 2 Google Drive sync every 2 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=2min
Persistent=true

[Install]
WantedBy=timers.target
`

	servicePath := filepath.Join(systemdDir, ServiceName+".service")
	timerPath := filepath.Join(systemdDir, ServiceName+".timer")

	if err := os.WriteFile(servicePath, []byte(serviceContents), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(timerPath, []byte(timerContents), 0o644); err != nil {
		return err
	}

	steps := [][]string{
		{"systemctl", "--user", "daemon-reload"},
		{"systemctl", "--user", "enable", "--now", ServiceName + ".timer"},
	}
	for _, args := range steps {
		cmd := exec.CommandContext(ctx, args[0], args[1:]...)
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("%v: %w: %s", args, err, out)
		}
	}

	return nil
}

// TimerStatus reports whether the sync timer is currently enabled and
// active, for the status view.
func TimerStatus(ctx context.Context) (enabled bool, active bool) {
	if runtime.GOOS != "linux" {
		return false, false
	}
	enabledOut, _ := exec.CommandContext(ctx, "systemctl", "--user", "is-enabled", ServiceName+".timer").CombinedOutput()
	activeOut, _ := exec.CommandContext(ctx, "systemctl", "--user", "is-active", ServiceName+".timer").CombinedOutput()
	return trimEq(enabledOut, "enabled"), trimEq(activeOut, "active")
}

// LastError returns a description of the last sync failure, or "" if the
// last run was fine. A player whose saves silently stopped syncing needs
// to be told, not left to notice on their own mid-campaign.
func LastError(ctx context.Context) string {
	if runtime.GOOS != "linux" {
		return ""
	}
	out, err := exec.CommandContext(ctx, "systemctl", "--user", "show", ServiceName+".service",
		"--property=ExecMainStatus", "--value").CombinedOutput()
	if err != nil {
		return ""
	}
	code, convErr := strconv.Atoi(strings.TrimSpace(string(out)))
	if convErr != nil || code == 0 {
		return ""
	}
	// Exit codes are rclone bisync's, documented at
	// https://rclone.org/bisync/#exit-codes
	switch code {
	case 7:
		return "The background sync hit a problem it can't recover from on its own. " +
			"Re-run Setup to rebuild the sync, then check both players' saves."
	case 1:
		return "The last background sync didn't finish. It will try again shortly; " +
			"if this keeps showing, check the log."
	default:
		return fmt.Sprintf("The background sync exited with code %d. Check the log for details.", code)
	}
}

func trimEq(b []byte, want string) bool {
	s := string(b)
	for len(s) > 0 && (s[len(s)-1] == '\n' || s[len(s)-1] == '\r' || s[len(s)-1] == ' ') {
		s = s[:len(s)-1]
	}
	return s == want
}

// LastSyncTime returns when the bisync service last ran successfully, for
// display ("last synced 2 minutes ago"). Returns zero time if unknown.
func LastSyncTime(ctx context.Context) time.Time {
	out, err := exec.CommandContext(ctx, "systemctl", "--user", "show", ServiceName+".service",
		"--property=ExecMainExitTimestamp", "--value").CombinedOutput()
	if err != nil {
		return time.Time{}
	}
	s := string(out)
	for len(s) > 0 && (s[len(s)-1] == '\n' || s[len(s)-1] == '\r') {
		s = s[:len(s)-1]
	}
	if s == "" {
		return time.Time{}
	}
	t, err := time.Parse("Mon 2006-01-02 15:04:05 MST", s)
	if err != nil {
		return time.Time{}
	}
	return t
}
