// Package bisync sets up a real local mirror directory kept in sync with a
// Google Drive folder via `rclone bisync` on a systemd user timer.
//
// This exists only because Google ships no native Linux sync client
// (unlike Dropbox and OneDrive, which stay out of this package entirely —
// they already maintain a real local folder themselves). A FUSE mount
// would be simpler to wire up, but it streams reads/writes over the
// network live, which is exactly the failure mode that makes Google
// Drive's own Windows "Streaming" mode unsafe for an actively-written
// save file. A real local directory, periodically reconciled, avoids that.
package bisync

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"

	"shogun2sync/internal/rcloneutil"
)

const (
	ServiceName = "shogun2sync-gdrive-bisync"

	// MinRcloneMajor/Minor is the oldest rclone that understands the flags
	// below. --recover, --max-lock, --resync-mode and the --conflict-*
	// family are all available together from rclone 1.71. On anything older the timer
	// would fail on every single run with "unknown flag", so this is
	// checked up front where we can still say something useful.
	MinRcloneMajor = 1
	MinRcloneMinor = 71
)

// Available reports whether this mechanism applies on this OS at all.
func Available() bool {
	return runtime.GOOS == "linux"
}

var versionRe = regexp.MustCompile(`v(\d+)\.(\d+)(?:\.(\d+))?`)

// Version returns the installed rclone's major and minor version.
func Version(ctx context.Context) (major, minor int, err error) {
	rclonePath, err := rcloneutil.Path()
	if err != nil {
		return 0, 0, err
	}
	out, err := exec.CommandContext(ctx, rclonePath, "version").Output()
	if err != nil {
		return 0, 0, fmt.Errorf("running rclone version: %w", err)
	}
	m := versionRe.FindStringSubmatch(string(out))
	if m == nil {
		return 0, 0, fmt.Errorf("could not read a version number out of %q", strings.TrimSpace(string(out)))
	}
	major, _ = strconv.Atoi(m[1])
	minor, _ = strconv.Atoi(m[2])
	return major, minor, nil
}

// CheckVersion reports a friendly error if rclone is too old to drive.
func CheckVersion(ctx context.Context) error {
	major, minor, err := Version(ctx)
	if err != nil {
		return err
	}
	if major > MinRcloneMajor || (major == MinRcloneMajor && minor >= MinRcloneMinor) {
		return nil
	}
	return fmt.Errorf(
		"rclone %d.%d is too old for reliable syncing (need %d.%d or newer). "+
			"Update it with your package manager, or install the current version from https://rclone.org/install/",
		major, minor, MinRcloneMajor, MinRcloneMinor)
}

// shellQuote wraps s for safe use inside single quotes in the generated
// script. A path is player-chosen and can contain anything, apostrophes
// included.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// systemdQuote protects one ExecStart argument. Unit files have their own
// quoting rules: percent starts a specifier, dollar starts environment
// expansion, and spaces split arguments even though no shell is involved.
func systemdQuote(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`%`, `%%`,
		`$`, `$$`,
	)
	return `"` + r.Replace(s) + `"`
}

// syncScript is the body of the script the timer runs.
//
// It's a real file rather than an inline `sh -c '...'` in the unit because
// that inline form has to survive two layers of quoting (systemd's, then
// the shell's), and gets both a percent sign and an apostrophe in a path
// wrong. A file has neither problem and is also something a player can
// read when they want to know what's running on their machine.
func syncScript(rclonePath, localDir, remote, logPath string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by Shogun 2 Save Sync. Edits will be overwritten.
set -u

RCLONE=%s
LOCAL=%s
REMOTE=%s
LOG=%s

# Keep support logs useful without allowing an unattended timer to grow one
# forever. One previous generation is enough for diagnosing a recurring job.
if [ -f "$LOG" ] && [ "$(wc -c < "$LOG")" -gt 1048576 ]; then
  rm -f "$LOG.1"
  mv "$LOG" "$LOG.1"
fi

"$RCLONE" bisync "$LOCAL" "$REMOTE" \
  --resilient --recover --max-lock 2m \
  --conflict-resolve newer --conflict-loser num --conflict-suffix conflict \
  --create-empty-src-dirs --drive-skip-gdocs \
  --log-file "$LOG" --log-format date,time -v
status=$?

if [ "$status" -eq 0 ]; then
  exit 0
fi

# Exit 7 is a critical abort: rclone will refuse every later run until a
# --resync re-establishes the baseline. Doing that automatically is
# normally dangerous, because --resync picks a winner and can overwrite
# the other player's newer save. The one case where it's safe is a local
# folder with nothing in it -- which is also the case that lands here most
# often, since bisync treats a legitimately empty folder as
# indistinguishable from a mount that dropped out.
if [ "$status" -eq 7 ] && [ -z "$(ls -A "$LOCAL" 2>/dev/null)" ]; then
  exec "$RCLONE" bisync "$LOCAL" "$REMOTE" --resync --resync-mode path2 \
    --create-empty-src-dirs \
    --log-file "$LOG" --log-format date,time -v
fi

exit "$status"
`, shellQuote(rclonePath), shellQuote(localDir), shellQuote(remote), shellQuote(logPath))
}

// Paths returns where the generated script and its log live.
func Paths() (scriptPath, logPath string, err error) {
	base, err := os.UserConfigDir()
	if err != nil {
		return "", "", err
	}
	dir := filepath.Join(base, "shogun2sync")
	return filepath.Join(dir, "gdrive-bisync.sh"), filepath.Join(dir, "gdrive-bisync.log"), nil
}

// EnsureMirror establishes (or re-establishes) a bisync baseline between
// localDir and remoteName:remoteSubfolder, then installs the systemd user
// units that will keep them in sync. It deliberately does not enable the
// timer: browser authorization happens before the player's final confirmation,
// so RunSetup activates the timer only after the save-folder link succeeds.
// remoteRootIsSyncFolder must only be true when the remote itself is scoped to
// the shared save folder; that explicit flag prevents an accidental empty
// subfolder from mirroring the player's entire Drive.
func EnsureMirror(ctx context.Context, remoteName, remoteSubfolder, localDir string, remoteRootIsSyncFolder bool) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("bisync is only needed on Linux")
	}
	rclonePath, err := rcloneutil.Path()
	if err != nil {
		return fmt.Errorf("rclone is not installed")
	}
	if _, err := exec.LookPath("systemctl"); err != nil {
		return fmt.Errorf("systemctl is not available")
	}
	if err := CheckVersion(ctx); err != nil {
		return err
	}
	if remoteSubfolder == "" && !remoteRootIsSyncFolder {
		// Without this an empty subfolder would mirror the player's entire
		// Drive into a game-saves folder.
		return fmt.Errorf("refusing to mirror the whole Drive: no sync folder was given")
	}

	if err := os.MkdirAll(localDir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", localDir, err)
	}

	scriptPath, logPath, err := Paths()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0o755); err != nil {
		return err
	}
	remote := remoteName + ":" + remoteSubfolder
	desiredScript := syncScript(rclonePath, localDir, remote, logPath)
	currentScript, _ := os.ReadFile(scriptPath)
	// Script flags and the bundled rclone path can change during an app
	// update without changing the mirror pair. Reinitialising merely because
	// the generated script improved would perform an unnecessary resync.
	current := string(currentScript)
	alreadyInitialised := strings.Contains(current, "\nLOCAL="+shellQuote(localDir)+"\n") &&
		strings.Contains(current, "\nREMOTE="+shellQuote(remote)+"\n")
	if !alreadyInitialised {
		// "newer" is deliberate. Bare --resync defaults to path1 and can
		// overwrite a newer save on Drive with an older local copy when a user
		// reconnects. Initialising a changed pair keeps the newest side and the
		// conflict flags preserve equal-time disagreements as visible copies.
		baseline := exec.CommandContext(ctx, rclonePath, "bisync", localDir, remote,
			"--resync", "--resync-mode", "newer",
			"--conflict-resolve", "newer", "--conflict-loser", "num",
			"--conflict-suffix", "conflict", "--create-empty-src-dirs")
		if out, err := baseline.CombinedOutput(); err != nil {
			return fmt.Errorf("initial sync failed: %w: %s", err, out)
		}
	}
	if err := os.WriteFile(scriptPath, []byte(desiredScript), 0o755); err != nil {
		return fmt.Errorf("writing %s: %w", scriptPath, err)
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	systemdDir := filepath.Join(home, ".config", "systemd", "user")
	if err := os.MkdirAll(systemdDir, 0o755); err != nil {
		return err
	}

	shPath, err := exec.LookPath("sh")
	if err != nil {
		return err
	}

	serviceContents := fmt.Sprintf(`[Unit]
Description=Sync the Shogun 2 save folder with Google Drive

[Service]
Type=oneshot
ExecStart=%s %s
`, systemdQuote(shPath), systemdQuote(scriptPath))

	timerContents := `[Unit]
Description=Run the Shogun 2 Google Drive sync every 2 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=2min
Persistent=true

[Install]
WantedBy=timers.target
`

	servicePath := filepath.Join(systemdDir, ServiceName+".service")
	timerPath := filepath.Join(systemdDir, ServiceName+".timer")

	if err := os.WriteFile(servicePath, []byte(serviceContents), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(timerPath, []byte(timerContents), 0o644); err != nil {
		return err
	}

	args := []string{"systemctl", "--user", "daemon-reload"}
	cmd := exec.CommandContext(ctx, args[0], args[1:]...)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%v: %w: %s", args, err, out)
	}

	return nil
}

// EnableMirror activates the prepared timer after setup's filesystem changes
// have completed successfully. Keeping this separate prevents a cancelled
// first-run wizard from leaving an undisclosed background job behind.
func EnableMirror(ctx context.Context) error {
	if runtime.GOOS != "linux" {
		return nil
	}
	cmd := exec.CommandContext(ctx, "systemctl", "--user", "enable", "--now", ServiceName+".timer")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("starting Google Drive background timer: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// DisableMirror stops the Linux background job without touching either side
// of the mirror. It is intentionally idempotent so Undo stays safe even when
// setup only got partway through.
func DisableMirror(ctx context.Context) error {
	if runtime.GOOS != "linux" {
		return nil
	}
	enabled, active := TimerStatus(ctx)
	if enabled || active {
		cmd := exec.CommandContext(ctx, "systemctl", "--user", "disable", "--now", ServiceName+".timer")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("stopping Google Drive background timer: %w: %s", err, strings.TrimSpace(string(out)))
		}
	}
	serviceOut, _ := exec.CommandContext(ctx, "systemctl", "--user", "is-active", ServiceName+".service").CombinedOutput()
	if trimEq(serviceOut, "active") || trimEq(serviceOut, "activating") {
		cmd := exec.CommandContext(ctx, "systemctl", "--user", "stop", ServiceName+".service")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("waiting for the active Google Drive sync to stop: %w: %s", err, strings.TrimSpace(string(out)))
		}
	}
	return nil
}

// TimerStatus reports whether the sync timer is currently enabled and
// active, for the status view.
func TimerStatus(ctx context.Context) (enabled bool, active bool) {
	if runtime.GOOS != "linux" {
		return false, false
	}
	enabledOut, _ := exec.CommandContext(ctx, "systemctl", "--user", "is-enabled", ServiceName+".timer").CombinedOutput()
	activeOut, _ := exec.CommandContext(ctx, "systemctl", "--user", "is-active", ServiceName+".timer").CombinedOutput()
	return trimEq(enabledOut, "enabled"), trimEq(activeOut, "active")
}

// LastError returns a description of the last sync failure, or "" if the
// last run was fine. A player whose saves silently stopped syncing needs
// to be told, not left to notice on their own mid-campaign.
func LastError(ctx context.Context) string {
	if runtime.GOOS != "linux" {
		return ""
	}
	out, err := exec.CommandContext(ctx, "systemctl", "--user", "show", ServiceName+".service",
		"--property=ExecMainStatus", "--value").CombinedOutput()
	if err != nil {
		return ""
	}
	code, convErr := strconv.Atoi(strings.TrimSpace(string(out)))
	if convErr != nil || code == 0 {
		return ""
	}
	// Exit codes are rclone bisync's, documented at
	// https://rclone.org/bisync/#exit-codes
	switch code {
	case 7:
		return "The background sync hit a problem it can't recover from on its own. " +
			"Re-run Setup to rebuild the sync, then check both players' saves."
	case 1:
		return "The last background sync didn't finish. It will try again shortly; " +
			"if this keeps showing, check the log."
	default:
		return fmt.Sprintf("The background sync exited with code %d. Check the log for details.", code)
	}
}

func trimEq(b []byte, want string) bool {
	s := string(b)
	for len(s) > 0 && (s[len(s)-1] == '\n' || s[len(s)-1] == '\r' || s[len(s)-1] == ' ') {
		s = s[:len(s)-1]
	}
	return s == want
}

// LastSyncTime returns when the bisync service last ran successfully, for
// display ("last synced 2 minutes ago"). Returns zero time if unknown.
func LastSyncTime(ctx context.Context) time.Time {
	statusOut, err := exec.CommandContext(ctx, "systemctl", "--user", "show", ServiceName+".service",
		"--property=ExecMainStatus", "--value").CombinedOutput()
	if err != nil || !trimEq(statusOut, "0") {
		return time.Time{}
	}
	out, err := exec.CommandContext(ctx, "systemctl", "--user", "show", ServiceName+".service",
		"--property=ExecMainExitTimestamp", "--value").CombinedOutput()
	if err != nil {
		return time.Time{}
	}
	s := string(out)
	for len(s) > 0 && (s[len(s)-1] == '\n' || s[len(s)-1] == '\r') {
		s = s[:len(s)-1]
	}
	if s == "" {
		return time.Time{}
	}
	t, err := time.Parse("Mon 2006-01-02 15:04:05 MST", s)
	if err != nil {
		return time.Time{}
	}
	return t
}
